//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::osu_team::Entity")]
    OsuTeam,
}

impl Related<super::osu_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OsuTeam.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
