[package]
name = "vocolo"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
actix-rt = "2.8.0"

tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.12"

reqwest = { version = "0.11", features = ["json"] }

async-trait = "0.1.66"
lazy_static = "1.4.0"

mongodb = "2.0"

uuid = { version = "1.3.0", features = ["v4", "fast-rng", "macro-diagnostics", "serde"] }
serde = { version = "1.0.152", features = ["derive"] }
derive_more = "0.99.17"

strum = { version = "0.24.1", features = ["derive"] }
strum_macros = "0.24.3"

rosu-v2 = "0.7.0"

oauth2 = "4.3.0"

dotenvy = "0.15.6"
