[package]
name = "vocolo"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.12"

axum = "0.6.18"

oauth2 = "4.3.0"
reqwest = { version = "0.11", features = ["json"] }

async-trait = "0.1.66"
lazy_static = "1.4.0"

mongodb = "2.0"

serde = { version = "1.0.152", features = ["derive"] }
derive_more = "0.99.17"

dotenvy = "0.15.6"
