[workspace]
members = [
    "bot",
	"common",
	"server",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
actix-web = "4.3.1"
actix-rt = "2.8.0"
common = { path = "common" }

tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.12"

async-trait = "0.1.66"
lazy_static = "1.4.0"

mongodb = "2.0"

uuid = { version = "1.3.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
serde = { version = "1.0.152", features = ["derive"] }

strum = { version = "0.24.1", features = ["derive"] }
strum_macros = "0.24.3"

rosu-v2 = "0.7.0"

serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
