//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::identities::Entity as Identities;
pub use super::osu_mappool::Entity as OsuMappool;
pub use super::osu_team::Entity as OsuTeam;
pub use super::osu_tournament::Entity as OsuTournament;
pub use super::sessions::Entity as Sessions;
pub use super::user::Entity as User;

